src/pie_modules/metrics/__init__.py
=> re-export `metrics` (and `statistics`) from `pytorch-ie`

poetry.lock, pyproject.toml, src/pie_modules/document/processing/tokenization.py, tests/document/processing/test_tokenization.py
This PR fixes which annotations are reported as missing after tokenization. When `tokenize_document()` returns multiple documents because of partitioning or windowing, the annotations are distributed on the respective result documents. This means, that each result document may lack some annotations but these may be still covered by other result docs. With this PR, we only report the annotations as missing that are not added to *any* of the result documents (e.g. spans because of alignment errors or relations because their arguments are in different result documents).
This requires: https://github.com/ChristophAlt/pytorch-ie/pull/390 (i.e. `pytorch-ie>=0.29.4`)
=> fix annotations that are reported as missing after tokenization

poetry.lock, pyproject.toml
This PR fixes a regression introduced in #14: the `OptimizerLRScheduler` type used in the EQA model requires `pytorch-lightning="^2.1.0" `
=> set `pytorch-lightning="^2.1.0" `

src/pie_modules/documents.py, src/pie_modules/metrics/squad_f1.py, src/pie_modules/taskmodules/extractive_question_answering.py, src/pie_modules/taskmodules/token_classification.py, tests/metrics/test_squad_f1.py, tests/models/test_extractive_question_answering.py, tests/taskmodules/test_extractive_question_answering.py, tests/test_documents.py
This adds the followign document types to `pie_modules.documents`:
- `TokenDocumentWithLabeledSpans`,
- `TokenDocumentWithLabeledPartitions`,
- `TokenDocumentWithLabeledSpansAndLabeledPartitions`,
- `TokenDocumentWithLabeledSpansAndBinaryRelations`, and
- `TokenDocumentWithLabeledSpansBinaryRelationsAndLabeledPartitions`.
This also renames `ExtractiveQADocument` and `TokenizedExtractiveQADocument` to `TextDocumentWithQuestionsAndExtractiveAnswers` and `TokenDocumentWithQuestionsAndExtractiveAnswers`, respectively (but maintains backwards compatibility for now).
=> add token document types

src/pie_modules/document/processing/tokenization.py
i.e. don't show them if verbose and don't break if strict_span_conversion. If tokenization is performed partition wise, the partition annotations are not required later on and entries get quite probably removed when windowing is applied, so this just pollutes the logs.
=> tokenization: don't regard missed partitions

src/pie_modules/models/base_models/bart_with_decoder_position_ids.py, tests/models/base_models/test_bart_with_decoder_position_ids.py
This PR adds a variant of the PyTorch BART model with a slight modification where the decoder accepts predefined position ids. If not provided, the original logic is used to create the position ids.
The model is based on the BartModel from Transformers `4.35.0`, i.e. https://github.com/huggingface/transformers/blob/v4.35.0/src/transformers/models/bart/modeling_bart.py.
Note: This also contains some minor modifications to make the code `mypy` (v1.4.1) compliant.
=> add `BartModelWithDecoderPositionIds` base model

poetry.lock, pyproject.toml, src/pie_modules/models/base_models/__init__.py, tests/models/base_models/test_bart_with_decoder_position_ids.py
This was missed in #26:
- export `BartModelWithDecoderPositionIds` directly from `models.base_models`
- set dependency `transformers = "^4.35.0"` because of `BartModelWithDecoderPositionIds `
=> post PR26 fixes

src/pie_modules/taskmodules/token_classification.py, tests/taskmodules/test_token_classification.py
=> skip overlapping spans instead of skipping whole documents

src/pie_modules/models/common/model_with_metrics_from_taskmodule.py
They need to be flattened, otherwise `LightningModule.log` complains.
=> fix logging nested metric dicts

src/pie_modules/taskmodules/metrics/common.py, src/pie_modules/taskmodules/metrics/precision_recall_and_f1_for_labeled_annotations.py, src/pie_modules/taskmodules/metrics/wrapped_layer_metrics_with_unbatch_and_decode_with_errors_function.py, tests/taskmodules/metrics/test_wrapped_layer_metrics_with_unbatch_and_decode_with_errors_function.py
With this PR, the state of the metric `WrappedLayerMetricsWithUnbatchAndDecodeWithErrorsFunction`, especially the error counts, are now correctly handled.
This also adds the abstract metric class `MetricWithArbitraryCounts` that provides the methods `inc_counts()` and `get_counts()` to easily handle counts lazily for arbitrary keys. This was outsourced from `PrecisionRecallAndF1ForLabeledAnnotations`.
=> Fix state of wrapped layer metrics with unbatch and decode with errors function

src/pie_modules/document/processing/tokenization.py
The original document may have more layers, but since result documents are of type `result_document_type`, we only check the layers of this type. This mitigates falsely reported errors, e.g. when calculating statistics where we use `result_document_type=TokenDocumentWithLabeledSpans`, but pass `TextDocumentWithLabeledSpansAndBinaryRelations` as input and the result does not contain any binary relations anymore (as expected).
=> fix `tokenize_document()`: check only for missing annotations in layers that are in the `result_document_type`

src/pie_modules/taskmodules/labeled_span_extraction_by_token_classification.py, src/pie_modules/taskmodules/re_text_classification_with_indices.py, tests/models/test_simple_token_classification.py, tests/models/test_token_classification_with_seq2seq_encoder_and_crf.py, tests/taskmodules/test_labeled_span_extraction_by_token_classification.py
With this PR, we
-  exclude `"O"` for token based metrics from `LabeledSpanExtractionByTokenClassificationTaskModule`, i.e. **micro- and macro-F1**, and
-  exclude `none_label`, i.e. "no_relation", for metrics from `RETextClassificationWithIndicesTaskModule`, i.e.  **micro-, macro, and per-label-F1**.
Fixes #43.
TODO:
- double-check if this is valid with Leo
=> Exclude none class for metrics (WIP)

src/pie_modules/annotations.py, src/pie_modules/documents.py
To have a single entry point and in preparation to move their implementations to `pie_modules`. This implements #11.
=> re-export `annotations` and `documents` from `pytorch_ie`

src/pie_modules/documents.py
This PR adds the following document types that contain `MultiSpan`s:
- `TextDocumentWithLabeledMultiSpans`, 
- `TextDocumentWithLabeledMultiSpansAndLabeledPartitions`, 
- `TextDocumentWithLabeledMultiSpansAndBinaryRelations`, and
- `TextDocumentWithLabeledMultiSpansBinaryRelationsAndLabeledPartitions`.
=> add multi-span documents

src/pie_modules/annotations.py, src/pie_modules/document/processing/tokenization.py, tests/document/processing/test_tokenization.py, tests/test_annotations.py
This also adds the annotation types `MultiSpan` and `LabeledMultiSpan`.
=> tokenization with `MultiSpan`s

poetry.lock, pyproject.toml, src/pie_modules/document/processing/__init__.py, src/pie_modules/document/processing/merge_spans_via_relation.py, tests/document/processing/test_merge_spans_via_relation.py
The PR adds the `document.processing.SpansViaRelationMerger`. From the docs:
```
Merge spans based on relations.
This processor merges spans based on binary relations. The spans are merged into a 
single span if they are connected via a relation with the specified link label. The 
processor handles both gold and predicted annotations.
Args:
relation_layer: The name of the relation layer in the document.
link_relation_label: The label of the relation that should be used to merge spans.
create_multi_spans: Whether to create multi spans or not. If `True`, multi spans
will be created, otherwise single spans that cover the merged spans will be
created.
result_document_type: The type of the document to return. This can be a class or
a string that can be resolved to a class. The class must be a …
```
=> implement `SpansViaRelationMerger`

src/pie_modules/models/components/pointer_head.py
this was broken if the input does not contain any full record
=> `PointerHead`: fix `increase_position_ids_per_record`

src/pie_modules/metrics/__init__.py, src/pie_modules/metrics/span_coverage_collector.py, tests/metrics/test_span_coverage_collector.py
From the class documentation:
```
Collects the coverage of Span annotations. It can handle overlapping spans.
If a tokenizer is provided, the span coverage is calculated in means of tokens, otherwise in
means of characters.
Args:
layer: The annotation layer of the document to calculate the span coverage for.
tokenize: Whether to tokenize the document before calculating the span coverage. Default is False.
tokenizer: The tokenizer to use for tokenization. Should be a PreTrainedTokenizer or a string
representing the name of a pre-trained tokenizer, e.g. "bert-base-uncased". Required if
tokenize is True.
tokenized_document_type: The type of the tokenized document or a string that can be resolved
to such a type. Required if tokenize is True.
tokenize_kwargs: Additional keyword arguments for …
```
=> implement `SpanCoverageCollector` statistic

src/pie_modules/utils/span.py, tests/utils/test_span.py
with the following methods:
- `are_nested`: Check if two spans are nested. Note that spans are considered to be nested if one is completely contained in the other, including the case where they are identical.
- `have_overlap`: Check if two spans have an overlap. Note that two spans that are touching each other are not considered to have an overlap. But two spans that are nested, including the case where they are identical, are considered to have an overlap.
- `distance_center`: Calculate the distance between the centers of two spans. The spans are defined by their start and end indices.
- `distance_inner`: Calculate the distance between the inner edges of two spans. In case of an overlap, the negative of the overlapping area is considered to be the distance.
- `distance_outer`: Calculate …
=> add span utils

src/pie_modules/models/base_models/bart_as_pointer_network.py, src/pie_modules/models/components/pointer_head.py, tests/models/components/test_pointer_head.py
This PR adds two more parameter, `decoder_position_id_mode` and `decoder_position_id_mapping`, to the `PointerHead` as well as to the `BartAsPointerNetwork` that allow for more control how the `position_ids` are created. The former defines  the general approach how to create position_ids and accepts one of the following values:
- `pattern`: requires a `decoder_position_id_pattern` that will be used to have a fixed pattern for all "records", e.g. `[0,0,1,0,0,1,1]` defines that all indices (positions 0, 1, 3, 4) and all labels (positions 2, 5, 6) get the same position id. This is as if previously just `decoder_position_id_pattern` was defined and, in fact, the way how the authors of [A Generative Model for End-to-End Argument Mining with Reconstructed Positional Encoding and Constrained …
=> create `position_ids` based on a mapping (`PointerHead`)

src/pie_modules/document/processing/text_span_trimmer.py, tests/document/processing/test_text_span_trimmer.py
Note that if `skip_empty=True` and `LabeledMultiSpan` did not have any slices in the beginning, it also gets removed. So it is ensured that after applying the trimmer, no empty multi spans are in the data at all what is usually wanted. 
This also adds the parameter `strict` (default: `True`) to disable strict behavior, i.e. allow that dependent annotations such as relations get removed without raising an error when an argument gets removed (because it is empty after trimming).
=> adjust `trim_text_spans()` to work with `LabeledMultiSpan`

src/pie_modules/document/processing/relation_argument_sorter.py, tests/document/processing/test_relation_argument_sorter.py
This PR improves the `RelationArgumentSorter` in the following ways:
- handle annotations that depend on the relations instead of raising an error, and
- allow `LabeledMultiSpan`s as relation arguments.
Note: this removes the `inplace` parameter to simplify the code. It works now **not inplace**.
=> improve `RelationArgumentSorter`

src/pie_modules/documents.py
This Pr adds the following document types:
- `TokenDocumentWithLabeledMultiSpans`,
- `TokenDocumentWithLabeledMultiSpansAndLabeledPartitions`,
- `TokenDocumentWithLabeledMultiSpansAndBinaryRelations`, and
- `TokenDocumentWithLabeledMultiSpansBinaryRelationsAndLabeledPartitions`.
=> add token document types with multi spans

src/pie_modules/metrics/__init__.py, src/pie_modules/metrics/relation_argument_distance_collector.py, tests/metrics/test_relation_argument_distance_collector.py
From the docstring:
```
Collects the distances between the arguments of relation annotations. For n-ary relations,
the distances between all pairs of arguments are collected. The distances can be calculated in
means of characters or tokens.
Args:
layer: The relation annotation layer of the document to collect the distances from.
distance_type: The type of distance to calculate. Can be "outer", "inner", or "center".
tokenize: Whether to tokenize the document before calculating the distance.
tokenizer: The tokenizer to use for tokenization. If a string is provided, the tokenizer is
loaded from the Hugging Face model hub. Required if tokenize is True.
tokenized_document_type: The type of document to return after tokenization. Required if
tokenize is True.
key_all: The key to use for the …
```
=> add `RelationArgumentDistanceCollector` statistic

src/pie_modules/document/processing/__init__.py, src/pie_modules/document/processing/merge_multi_spans.py, tests/document/processing/test_merge_multi_spans.py
This PR adds the `MultiSpanMerger` document processor. From the dosctring:
``` 
Merges MultiSpans in the given layer of the input document into Spans in the result
document.
Args:
layer: The name of the annotation layer that contains the MultiSpans to merge.
result_document_type: The type of the result document.
target_layer: The name of the annotation layer in the result document where the merged
Spans should be added. If not provided, the same name as the input layer will be used.
```
=> implement `MultiSpanMerger`

poetry.lock, pyproject.toml, src/pie_modules/taskmodules/pointer_network_for_end2end_re.py, tests/taskmodules/test_pointer_network_for_end2end_re.py
This PR removes the parameter `span_layer_name` from the `PointerNetworkTaskModuleForEnd2EndRE` because we can infer this from the target of the relation annotation layer. It is breaking because: 1) the parameter is removed, and 2) we require `pytorch-ie>=0.30.1` because of https://github.com/ArneBinder/pytorch-ie/pull/407.
=> remove parameter `span_layer_name` from `PointerNetworkTaskModuleForEnd2EndRE`

src/pie_modules/models/base_models/bart_as_pointer_network.py, src/pie_modules/models/components/pointer_head.py, tests/models/base_models/test_bart_as_pointer_network.py, tests/models/components/test_pointer_head.py
remove parameter increase_position_ids_per_record from BartAsPointerNetworkConfig and from PointerHead; do not automatically select decoder_position_id_mode=pattern if decoder_position_id_pattern is provided
=> cleanup `PointerHead` logic  regarding `decoder_position_id_mode`

src/pie_modules/models/base_models/bart_as_pointer_network.py
Simple change to allow task learning rate config in the `BartAsPointerNetworkConfig` that controls the learning rate applied to the `head` parameters  If `task_lr` is not provided, the `lr` is automatically used.
=> add task lr config for bart_as_pointer_network

poetry.lock, pyproject.toml, src/pie_modules/annotations.py, src/pie_modules/documents.py
This PR removes the annotation types:
- MultiSpan
- LabeledMultiSpan
and the document types:
- TextDocumentWithLabeledMultiSpans,
- TextDocumentWithLabeledMultiSpansAndBinaryRelations, 
- TextDocumentWithLabeledMultiSpansAndLabeledPartitions, and
- TextDocumentWithLabeledMultiSpansBinaryRelationsAndLabeledPartitions
Theses types are re-exported so that there is no change on the surface.
Note that, in contrast to the previous implementations, the annotation types in PyTorch-IE implement `resolve()`.
This requires [`pytorch-ie>=0.30.3`](https://github.com/ArneBinder/pytorch-ie/releases/tag/v0.30.3).
=> use multi span annotations and documents from PyTorch-IE

poetry.lock, pyproject.toml, src/pie_modules/document/processing/__init__.py, src/pie_modules/document/processing/sentence_splitter.py, tests/document/processing/test_sentence_splitter.py
This PR adds `pie_modules.document.processing.NltkSentenceSplitter`. From its docstring:
```
A document processor that adds sentence partitions to a TextDocumentWithLabeledPartitions document.
It uses the NLTK Punkt tokenizer to split the text of the document into sentences. See
https://www.nltk.org/api/nltk.tokenize.html#nltk.tokenize.punkt.PunktSentenceTokenizer for more information.
Args:
partition_layer_name: The name of the partition layer to add the sentence partitions to. This layer
must be an AnnotationLayer of LabeledSpan annotations.
text_field_name: The name of the text field in the document to split into sentences.
sentencizer_url: The URL to the NLTK Punkt tokenizer model.
```
=> add `NltkSentenceSplitter`

src/pie_modules/document/processing/sentence_splitter.py, tests/document/processing/test_sentence_splitter.py
This PR:
- adds `inplace` parameter to `NltkSentenceSplitter`; and
- calling a `NltkSentenceSplitter` returns the result document (independent of `inplace` value).
Note: CI fails because there is currently an issue with https://huggingface.co.
=> `NltkSentenceSplitter` returns the result document

src/pie_modules/taskmodules/re_text_classification_with_indices.py
`NaryRelation` was not yet allowed in `.encode_target()`
=> fix `RETextClassificationWithIndicesTaskModule` for `NaryRelation`

src/pie_modules/taskmodules/re_text_classification_with_indices.py, tests/taskmodules/test_re_text_classification_with_indices.py
New output:
- add `all_relations` column with summary (only if there is more then 1 relation type in a table). note that we exclude the `no_relations`
- add `used %` row (only if `used` row exists)
Example:
```md
|           |   org:founded_by |   per:employee_of |   per:founder |   all_relations |
|:----------|-----------------:|------------------:|--------------:|----------------:|
| available |                2 |                 3 |             2 |               7 |
| used      |                2 |                 3 |             2 |               7 |
| used %    |              100 |               100 |           100 |             100 |
```
=> extend statistics for re_classification_with_indices

poetry.lock, pyproject.toml, src/pie_modules/document/processing/tokenization.py, tests/document/processing/test_tokenization.py
This PR does the following:
- `text_based_document_to_token_based()` and `token_based_document_to_text_based()` save dicts in `added_annotations` (instead of just the list of original ones that got handled)
- add a parameter `added_annotations` to `tokenize_document` (works similar as in `text_based_document_to_token_based()` and `token_based_document_to_text_based()`)
- add documentation to all three methods
Note: This requires `pytorch-ie>=0.31.0` because of https://github.com/ArneBinder/pytorch-ie/pull/418, so this is a breaking change.
=> tokenization saves a mapping from original to new annotations in `added_annotations`

src/pie_modules/taskmodules/labeled_span_extraction_by_token_classification.py, src/pie_modules/taskmodules/re_text_classification_with_indices.py, tests/models/test_simple_token_classification.py, tests/models/test_token_classification_with_seq2seq_encoder_and_crf.py, tests/taskmodules/test_labeled_span_extraction_by_token_classification.py, tests/taskmodules/test_re_span_pair_classification.py, tests/taskmodules/test_re_text_classification_with_indices.py
Originally, we use the id of `no_relation` (relation extraction) or `O` (token classification) as `ignore_index`. However, this disrespects all errors where the model predicts a valid class (not  `no_relation` / `O`), but the gold data is actually `no_relation` / `O` because using them as ignore_index simply masks away all entries where the gold data has the respective index. This PR changes that behavior by not setting ignore_index to these values (we set it just to the padding indices which really indicate invalid values for gold *and* predictions). Note that this may produce quite high micro values because there are in general a lot of `no_relation` / `O`.
affected taskmodules: 
- `LabeledSpanExtractionByTokenClassificationTaskModule` 
- `RETextClassificationWithIndicesTaskModule`
=> fix taskmodule metrics (`ignore_index`)

src/pie_modules/taskmodules/common/__init__.py, src/pie_modules/taskmodules/common/taskmodule_with_document_converter.py, tests/taskmodules/common/test_taskmodule_with_document_converter.py
This implements the abstract class `TaskModuleWithDocumentConverter`. It allows to easily create "wrapped" taskmodules which have the same core functionality as the base taskmodule, but require to have some document conversion before the encoding / after prediction attachments.
It requires to implement the following methods:
```python
@abstractmethod
def _convert_document(self, document: DocumentType) -> ConvertedDocumentType:
"""Convert a document of the taskmodule document type to the 
expected document type of the wrapped taskmodule.
Args:
document: the input document
Returns: the converted document
"""
pass
@abstractmethod
def _integrate_predictions_from_converted_document(
self,
document: DocumentType,
converted_document: ConvertedDocumentType,
) -> …
```
=> implement `TaskModuleWithDocumentConverter`

src/pie_modules/document/processing/text_pair.py, tests/document/processing/test_text_pair.py
This changes `construct_text_pair_coref_documents_from_partitions_via_relations()` to add the following to metadata:
- `original_doc_id`: doc id of the original document where the `text` is from
- `original_doc_id_pair`: doc id of the original document where the `text_pair` is from
- `original_doc_span`: a dict with `start` and `end` keys indicating where the `text` is from with respect to the original doc
- `original_doc_span_pair`: a dict with `start` and `end` keys indicating where the `text_pair` is from with respect to the original doc
Also, this gets correctly propagated in`add_negative_coref_relations()`, when available.
Finally, this adds the parameter `enforce_same_original_doc_id` to `add_negative_coref_relations()`. If enabled, only negatives where both `text` and `text_pair` …
=> `enforce_same_original_doc_id` parameter & improved text pair metadata

src/pie_modules/taskmodules/metrics/wrapped_metric_with_prepare_function.py, tests/taskmodules/test_re_text_classification_with_indices.py
This allows `WrappedMetricWithPrepareFunction` to work with metrics from `torchmetrics` with empty batches (e.g. `torchmetrics.F1Score` crashes in these cases). We check if an input is an empty batch and do not call forward/update in these cases (in the case of forward we return `None`).
=> fix `micro/f1_without_tn` in RE taskmodule

poetry.lock, pyproject.toml, src/pie_modules/document/processing/merge_spans_via_relation.py, src/pie_modules/document/processing/sentence_splitter.py, src/pie_modules/models/token_classification_with_seq2seq_encoder_and_crf.py
... to reduce potential dependency conflicts when not using such optional functionality. 
In detail, we move (now lazily imported in):
- `flair` (`FlairSegtokSentenceSplitter`)
- `nltk` (`NltkSentenceSplitter`)
- `pytorch-crf`: (`TokenClassificationModelWithSeq2SeqEncoderAndCrf`)
- `networkx`: (`SpansViaRelationMerger`)
=> move non-core dependencies to dev group

src/pie_modules/metrics/span_length_collector.py, tests/metrics/test_span_length_collector.py
that restriction was not necessary for this metric since we normalize over all existing values, not per document (i.e. we do not need to respect missing zero values)
=> allow all aggregation methods for `SpanLengthCollector` when using `labels=INFERRED`

src/pie_modules/taskmodules/pointer_network_for_end2end_re.py, tests/taskmodules/test_pointer_network_for_end2end_re.py
- skip relation when another relation with same arguments and **same label** was already encoded
- skip whole task encoding if another relation with same arguments and a **different label** was already encoded
=> `PointerNetworkTaskModuleForEnd2EndRE`: skip duplicated / conflicting relations druing encoding

src/pie_modules/document/processing/tokenization.py, tests/document/processing/test_tokenization.py
This adds the parameter `strip_spans` to `text_based_document_to_token_based` and to `tokenize_document`:
```
strip_spans (bool, optional): If True, strip the whitespace from the character spans before
converting them to token spans. Defaults to False.
```
**This is breaking** because, now:
- empty spans (i.e. start==end) are considered as not tokenizable (in any case, not just if the (start/end) index points outside of a token)
- multi-spans without any slices are not tokenizable
- multi-spans are not tokenizable if *all* slices are not tokenizable (individual slices get dropped silently)
=> tokenization: strip spans in `text_based_document_to_token_based`

.pre-commit-config.yaml, README.md, src/pie_modules/models/base_models/bart_as_pointer_network.py, src/pie_modules/models/components/pooler.py, src/pie_modules/taskmodules/common/taskmodule_with_document_converter.py, src/pie_modules/taskmodules/cross_text_binary_coref.py, src/pie_modules/taskmodules/pointer_network_for_end2end_re.py, src/pie_modules/taskmodules/re_span_pair_classification.py, tests/document/processing/test_merge_spans_via_relation.py
Process:
1. add dummy commit to markdown file (readme.md) to trigger error (on PR CI workflows, pre-commit gets called only on modified files)
2. call `pre-commit autopudate` to update hooks to latest version, but revert change for `docformatter`
3. call `pre-commit run -a` to make pre-commit happy
4. revert dummy commit
This fixes the following CI workflow error (may just occur on merge into main because of modified files check in PR workflows):
```
...
mdformat.................................................................Failed
- hook id: mdformat
- exit code: 1
Traceback (most recent call last):
File "/home/runner/.cache/pre-commit/repox111q2_2/py_env-python3/bin/mdformat", line 8, in <module>
sys.exit(run())
File "/home/runner/.cache/pre-commit/repox111q2_2/py_env-python3/lib/python …
```
=> update pre-commit hooks

src/pie_modules/taskmodules/re_text_classification_with_indices.py, tests/taskmodules/test_re_text_classification_with_indices.py
Adds `argument_type_whitelist: List[List[str]]` parameter used by `_add_candidate_relations()`.
This allows adding candidates only of pre-defined argument type pairs.
E.g. when `argument_type_whitelist=[['ORG','PER']]` only relations with head.label='ORG' and tail.label='PER' will be added.
TODO:
metric | baseline | with whitelist 
-- | -- | --
quality (micro f1) | 0.7597 (±0.0037) | 0.7737 (±0.0042)
Inference time | 83.56 | 13.5 (±0.3)
=> add  `argument_type_whitelist` parameter to `RETextClassificationWithIndicesTaskModule`

.github/workflows/code-quality-main.yaml, .github/workflows/code-quality-pr.yaml, .github/workflows/labeler.yml, .github/workflows/release.yml, .github/workflows/test.yaml
especially for `actions/cache` to fix the version issue, see https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down for context
**Note that our actions did not succeed although we use `actions/cache >= 4` (`v4.2.1`).**
Same as https://github.com/ArneBinder/pie-datasets/pull/170.
=> CI: define only major version for all actions from Github

src/pie_modules/taskmodules/re_text_classification_with_indices.py, tests/taskmodules/test_re_text_classification_with_indices.py
If there are multiple relations with same pair of arguments, `handle_relations_with_same_arguments` defines if we remove both of them (`keep_none`) or keep the first one (`keep_first`). Full duplicates (if relation label is also the same) are not affected by this, one relation will be kept and a warning shown.
Note that if `collect_statistics=True`, final statistics do not include such "full duplicates" either as 'available' nor as 'skipped'. Also, **warnings about elements collected in the statistics**, e.g. skipped relations with same arguments, **will not be shown if `collect_statistics=True`.**
**This PR changes the default behavior to `keep_none`, that's why is labeled as `breaking` (previously it was implicitly `keep_first`).** Doing so prevents the model from learning conflicting …
=> add `handle_relations_with_same_arguments` parameter to `RETextClassificationWithIndicesTaskModule`

src/pie_modules/taskmodules/labeled_span_extraction_by_token_classification.py, tests/models/test_simple_token_classification.py, tests/models/test_token_classification_with_seq2seq_encoder_and_crf.py, tests/taskmodules/test_labeled_span_extraction_by_token_classification.py
From the docstring:
`combine_token_scores_method`: Method to combine the token scores to a span score. Options are "mean", "max", "min", and "product". Default: "mean".
Note that "mean" was the implicit behavior until now, so this is **not** breaking.
=> add parameter `combine_token_scores_method` for `LabeledSpanExtractionByTokenClassificationTaskModule`

src/pie_modules/document/processing/merge_spans_via_relation.py, tests/document/processing/test_merge_spans_via_relation.py
from the docstring:
`combine_scores_method`: The method to combine the scores of the relations and the spans. The options are "mean" and "product". The default is "mean".
=> add `combine_scores_method` to `SpansViaRelationMerger`

src/pie_modules/taskmodules/re_text_classification_with_indices.py, tests/taskmodules/test_re_text_classification_with_indices.py
which is the token based version of `max_argument_distance` (which is character based). Also adds and `max_argument_distance_type_tokens` (in analogy to `max_argument_distance_type`).
Important: The distance is calculated **without any marker tokens**!
=> add parameter `max_argument_distance_tokens` to `RETextClassificationWithIndicesTaskModule`

src/pie_modules/utils/sequence_tagging/encoding.py
-  add return types to `boul_tags_to_spans` and to `tag_sequence_to_token_spans`
-  clarify that decoded span ends are inclusive (`iob2_tags_to_spans`, `bioul_tags_to_spans`, `boul_tags_to_spans`, `tag_sequence_to_token_spans`)
=> improve `utils.sequence_tagging.encoding` (typing and docs)

src/pie_modules/models/components/pooler.py, tests/models/components/test_pooler.py
This allows to pass a parameter `aggregate` to the pooler config:
- `max` (default): create a `SpanMaxPooler` (as before)
- `mean`: create a `SpanMeanPooler`
=> implement `SpanMeanPooler` and add it to `get_pooler_and_output_size` logic

src/pie_modules/taskmodules/common/mixins.py, tests/taskmodules/common/test_mixins.py, tests/taskmodules/test_cross_text_binary_coref.py
- `src/pie_modules/taskmodules/common/mixins.py`
* add a lazy-getter `get_none_label_for_statistics()` to `RelationStatisticsMixin`
- `tests/taskmodules/common/test_mixins.py`
* update tests
Statistics are now getting `self.none_label` only once, when `none_label` is needed for the first time.
If it was not set - default value is used instead and a warning logged.
Value is saved in `self._statistics_none_label` for further use.
=> add `none_label` parameter to `RelationStatisticsMixin`
